apiVersion: v1
kind: Pod
metadata:
  labels:
    hello: world
    run: mynginx
  name: mynginx
spec:
  containers:
  - name: mynginx
    image: nginx
    
## 생성
# kubectl apply -f ~/k8s_mlops/pod/2-labels.yaml
## 확인
# kubectl get pod -o wide -w
## 라벨 확인
# kubectl get pod mynginx -L hello
# kubectl get pod mynginx -L run
## 라벨 추가 지정
# kubectl label pod mynginx meta=jeongmin
# kubectl get pod mynginx -L run
## 라벨로 필터링
# kubectl get pod -l run
# kubectl get pod -l run=mynginx
## 삭제
# kubectl delete -f ~/k8s_mlops/pod/2-labels.yaml
## 확인
# kubectl get pod