apiVersion: v1
kind: Pod
metadata:
  name: mynginx
spec:
  containers:
  - name: mynginx
    image: nginx
    volumeMounts:
    - name: myvolume
      mountPath: /container-volume

  volumes:
  - name: myvolume
    hostPath:
      path: /home

## 생성
# kubectl apply -f ~/k8s_mlops/pod/3-volume.yaml
## 확인
# kubectl get pod -o wide -w
## 마운트된 볼륨 확인
# kubectl exec volume -- ls /container-volume
## 삭제
# kubectl delete -f ~/k8s_mlops/pod/3-volume.yaml