apiVersion: batch/v1
kind: Job
metadata:
  name: ml-job
spec:
  template:
    spec:
      containers:
        - name: ml
          image: silverstar456/k8s_mlops:hpo
          args: ["3", "softmax"] # args 집어넣기
          # 리소스 사용량
          resources:
            limits: 
              cpu: "1"
              memory: "5Gi"
      restartPolicy: Never
  backoffLimit: 0 # 실패시 다시시작 옵션