apiVersion: apps/v1
kind: Deployment
metadata:
  name: replicas
spec:
  replicas: 3
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx

# kubectl apply -f ~/k8s_mlops/deployment/2-replicas.yaml
# kubectl get pod
# kubectl describe deployment replicas
# kubectl delete -f ~/k8s_mlops/deployment/2-replicas.yaml