apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollup
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25% # 중지된 파드 한도
      maxSurge: 25% # 새로운 파드 생성 한도
  selector:
    matchLabels:
      run: nginx
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx

# kubectl apply --record -f ~/k8s_mlops/deployment/3-rollingupdate.yaml
# kubectl get deployment
## 이미지 업데이트
# kubectl set image deployment rollup nginx=nginx:1.9.1 --record
# kubectl get pod
# kubectl delete -f ~/k8s_mlops/deployment/3-rollingupdate.yaml