apiVersion: batch/v1
kind: Job
metadata:
  name: ml-job
spec:
  template:
    spec:
      containers:
        - name: ml
          image: silverstar456/k8s_mlops:minio
          args: ["34.135.254.174", "zfYhCeQ6ewBFWXKw", "xELjiQ32uKx1xy3Td8VlQhYv8QUmhDsq"]
      restartPolicy: Never
  backoffLimit: 0 # 실패시 다시시작 옵션


# docker build -t silverstar456/k8s_mlops:minio ~/k8s_mlops/storage/minio-test
# docker login
# docker push silverstar456/k8s_mlops:minio

# kubectl apply -f 1-minio.yaml
# kubectl get pod
# kubectl logs -f {pod_name}