apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-storage
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  #storageClassName: nfs-storage
  storageClassName: standard

# kubectl apply -f ~/k8s_mlops/storage/1-nfs-storage-pvc.yaml
# kubectl get pvc
# kubectl get sc