apiVersion: batch/v1
kind: Job
metadata:
  name: model-job
spec:
  template:
    spec:
      containers:
      - name: ml
        image: tensorflow/tensorflow
        volumeMounts:
        - mountPath: "/model_storage"
          name: model-storage
      restartPolicy: Never
      volumes:
      - name: model-storage
        persistentVolumeClaim:
          claimName: data1-minio1-ss-0-2
  backoffLimit: 0

# docker build -t silverstar456/k8s_mlops:model-storage ~/k8s_mlops/storage/model-storage
# kubectl apply -f ~/k8s_mlops/storage/2-model-job.yaml
# kubectl get pod
# kubectl logs {pod-name}